model_name=None
#server_name='deepseek'
#server_name='vllm'; 
#server_name='openai'; model_name='Qwen3-14B'
#server_name = 'local'
#server_name='Claude'
#server_name='llama.cpp'
#server_name='openai'; model_name='gpt-4.1-mini'
#server_name='openai'; model_name='gpt-4.1'
server_name='openai'; model_name='gpt-4.1-nano'
#server_name='openai'; model_name='gpt-4o'
#server_name='gemini'
#server_name='gemini-pro'
#server_name='Grok' 
#server_name='Cohere'
#server_name='openrouter'; model_name='google/gemini-2.5-flash' 
#server_name='openrouter'; model_name='mistralai/mixtral-8x7b-instruct' #google/gemini-2.0-flash-preview'
#server_name='openrouter'; model_name='qwen/qwen3-32b'
#server_name='openrouter'; model_name='arcee-ai/virtuoso-large'
